#!/bin/bash

# TEST: Compare the new stack's index.html to our local one
curl -s 'http://'`grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" output.json` > test_output.html
test_output=`cat test_output.html`
original=`cat index.html`
if [ "$test_output" = "$original" ]; then
  echo 'TEST PASSED: Webpage contents read "Automation for the People"'
  open 'http://'`grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" output.json`
else
  echo 'TEST FAILED!'
fi
